I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 175, in script
    label choice1picked:
  File "game/script.rpy", line 175, in script
    label choice1picked:
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\rahma\Downloads\renpy-8.1.1-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\Users\rahma\Downloads\renpy-8.1.1-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "C:\Users\rahma\Downloads\renpy-8.1.1-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "C:\Users\rahma\Downloads\renpy-8.1.1-sdk\renpy\execution.py", line 953, in run_context
    context.run()
  File "game/script.rpy", line 175, in script
    label choice1picked:
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 175, in script
    label choice1picked:
  File "C:\Users\rahma\Downloads\renpy-8.1.1-sdk\renpy\execution.py", line 61, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
Dead Ringer 1.0
Fri Aug  4 11:01:24 2023
